### ISSUE TITLE
Revise notifications.

### ISSUE THREAD

**Issue by Kimel1** [ctrlplusb/react-universally#231]
If anyone tired because of thousands notifications, then go 
`/tools/utils.js ` and comment  102-106 lines 
```
export function createNotification(options : NotificationOptions) {
  const title = `${options.title.toUpperCase()}`;

/*   notifier.notify({
    title,
    message: options.message,
    open: options.open,
  }); */

  const level = options.level || 'info';
  const msg = `==> ${title} -> ${options.message}`;

  switch (level) {
    case 'warn': console.log(colors.red(msg)); break;
    case 'error': console.log(colors.bgRed.white(msg)); break;
    case 'info':
    default: console.log(colors.green(msg));
  }
}
```

**Comment by ctrlplusb** [comment]
We could add this as a configuration option within `./config/private/project.js`

**Comment by ctrlplusb** [comment]
I don't know about removing them completely, but I think we can choose a bit more wisely which notifications should be displayed. The console should be the main source of viewing what is going on, whilst the notifications should be for the critical/primary events only.

**Comment by Kimel1** [comment]
@ctrlplusb If we talk about development, I think there is no important events for notification. If developments server will crush then I will notice this without any warnings. 

If we talk about production, then notification is useless because usually production server is remote and you just haven't see any notification. 

So, I don't know any cases where notification can be useful.

**Comment by ctrlplusb** [comment]
Thoughts @strues @enten @bkniffler @carsonperrotti @lucianlature?

**Comment by strues** [comment]
At first I was not a big fan of the notifications. However, once an application gets bigger and compilation times increase, I find it to be a benefit. What I mean by that is, in the instances where you need a hard refresh, or waiting on the server to come online, the notification saying the server is running on XX is helpful.

On the other hand, I can see how the notifications might seem gimicky or unnecessary.

**Comment by bkniffler** [comment]
Hey there, I'd like defend the notifications. It surely depends on how your dev environment looks like, but on my 13" Macbook, where I use 3 fullscreen windows (editor, browser, terminal), it is extremely useful to see whats going on without having to check the terminal. Imagine you start the server, go in browser to prepare a few things, the notification pops up, you load the page. Thats very cool! 

But yeah, maybe its a little too much. The things that I really find interesting is: 
- Server started (with port)
- Webpack has rebuild
- Webpack has failed

What I don't really need is
- Multiple notifications on start
- Webpack is starting to rebuild (sometimes its good because the server might have crashed)

What could also help is a notification if your server crashes.

Also I can understand that for others, the notifications might be annoying, so a flag to disable them via environment var might be useful.

**Comment by enten** [comment]
Notifications are useful for development purposes (running hot development environment or building bundles).

I think it's a good idea to add notification options in the `project.js`.

In production: we should run node with the server entry point only. So, notifications doesn't append.

**Comment by ctrlplusb** [comment]
Ok, I think I have cleaned this up quite nicely.

On `incubator/master`

**Comment by ctrlplusb** [comment]
Fixed some bugs too.

**Comment by peshi** [comment]
@ctrlplusb I am still getting 23 notification whenever running develop, every time there's a code save.

**Comment by enten** [comment]
I suggest to associate the notifier with the logger.

## Use case

When the log level is "info", we only show notifications for that level or higher.

## Implementation example

[See here](https://gist.github.com/enten/54c45d5056e63b30b16739aadd7de0d1)

## Usage example

```javascript
// test.js
const createLogger = require('./log')

const envFalseValues = [undefined, '0', 'false', 'N', 'NO', 'n', 'no']
const isEnvFalseValue = (val) => envFalseValues.indexOf(val) > -1

const Log = createLogger({
  level: process.env.LOG_LEVEL,
  notifs: !isEnvFalseValue(process.env.LOG_NOTIFS),
  prefix: 'RU',
  prefixStyles: ['bold', 'white'],
  theme: {
    info: ['blue']
  }
})

Log.info('info message')
Log.info.notify('info notification')

Log.debug('debug message')
Log.debug.notify('debug notification')

// $ node test.js
// # Note: only info notification will be shown
//
// info RU info message
// info RU ✓ info notification

// $ LOG_LEVEL=debug node test.js
// # Note: info and debug notifications will be shown
//
// info RU info message
// info RU ✓ info notification
// debu RU debug message
// debu RU debug notification

// $ LOG_NOTIFS=no LOG_LEVEL=debug node test.js
// # Note: no notifications will be shown
//
// info RU info message
// info RU ✓ info notification
// debu RU debug message
// debu RU debug notification
```
